version: '3.8'
services:
  app:
    image: customer-processor
    container_name: customer-processor-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: customer-processor-db
    environment:
      SA_PASSWORD: myPass123!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
